### ISSUE TITLE
Request to add the Common Core Ontology to the namespace

### ISSUE THREAD

**Issue by JKReynolds** [solid/solid-namespace#12]
Hello, my team primarily uses the Common Core Ontology (CCO) when doing development. I have made a pull request and would like to add this to the namespace.

For more information about the CCO...
https://www.cubrc.org/index.php/data-science-and-information-fusion/ontology
https://www.nist.gov/sites/default/files/documents/2019/05/30/nist-ai-rfi-cubrc_inc_004.pdf

If anyone has questions, feel free to respond.

**Comment by TallTed** [comment]
Fixed by #8
