### ISSUE TITLE
Export aliases

### ISSUE THREAD

**Issue by ludwigschubi** [solid/solid-namespace#16]
I have a use case in which I would like to make use of the aliases that are used in vocab(). I am writing a parser for which I want to check whether a found prefix is equal to an alias in the solid-namespaces.

**Comment by bourgeoa** [comment]
Good idea, I also have a use case. It avoids to maintain a solid prefix list in code.

**Comment by ludwigschubi** [comment]
to not break the default export one would have to change the module syntax to es6 module syntax i think (https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6)

**Comment by ludwigschubi** [comment]
@bourgeoa cool how do you do it?

**Comment by ludwigschubi** [comment]
I guess i can work around this by using `Object.keys(ns)` 👍
